function ret = particleNull(numParticles)
    ret = struct('x', zeros(numParticles, 1), ...
        'y', zeros(numParticles, 1), ...
        'vx', zeros(numParticles, 1), ...
        'vy', zeros(numParticles, 1), ...
        'vz', zeros(numParticles, 1) ...
        );
end
