function plotIonHolesSideBySide()
    f = figure;
    
    numSideBySide = 4;
    holeBeg = 5532;
    holeEnd = 6082;
    templatePlot(holeBeg, holeEnd, numSideBySide, 4);
    
    templatePlot(6379, 7328, numSideBySide, 3);

    holeBeg = 7363;
    holeEnd = 7907;
    templatePlot(holeBeg, holeEnd, numSideBySide, 2);
    
    templatePlot(8455, 8782, numSideBySide, 1);
    
    annotation('textbox', [0 0.9 1 0.1], ...
    'String', 'Hot Electrons: Time = 160000', ...
    'EdgeColor', 'none', ...
    'HorizontalAlignment', 'center')
    
    print(f, '-dpng', 'sideBySideVxVy');
end

function templatePlot(start, stop, numSideBySide, plotNumber)
    subplotTitle = strcat('y=', num2str(start), '-', num2str(stop));
    plotVxVyRange('ele_160000', ...
                  512/2-50, 512/2+50, ...
                  start, stop, ...
                  'hotOnly', 'noCull', ...
                  'numBins', 50, ...
                  'vxMin', -5, ...
                  'vxMax', 5, ...
                  'vyMin', -5, ...
                  'vyMax', 5, ...
                  'plotVxVy', ...
                  'subplotArgs', [1 numSideBySide, plotNumber], ...
                  'subplotTitle', subplotTitle ...
                  );
    fclose('all');
end