function plotPotentPerformance()
   f = figure;
   x = csvread('potentPerformance.csv', 1, 0);
   widthList = [32 64 128 256 512];
   plot(widthList, x(:, 1), ':', ...
        widthList, x(:, 2), '--', ...
        widthList, x(:, 3), '-.', ...
        widthList, x(:, 4), '-' ...
        );
   xlabel('Num Columns');
   ylabel('Milliseconds');
   legend( ...
       'Height = 2500', ...
       'Height = 5000', ...
       'Height = 7500', ...
       'Height = 10000' ...
       );
   axis([32 512 0 24]);
   saveSameSize(f, 'format', '-dpdfwrite', 'file', 'potent2Performance');
end